
[general]
	selected_macro = 5

[general_macro_config]
	quick_death = true
	quick_death_distance = 5

[cactus]
	start_direction = 0

[cane]
	start_direction = 0
	timer_mode = 0
	row_time = "60"

[mushroom]
	start_direction = 0
	timer_mode = 1
	row_time = "60"

	[mushroom.obsidian_pause]
		pause_time = 1
		switch_direction = true
		enabled = true

[fail-safes]

	[fail-safes.world_change]
		world_change = false
		warp_back_on_world_change = false
		warp_back_command = "/warp garden"

	[fail-safes.block_change]
		block_change = false

	[fail-safes.slot_change]
		slot_change = false

	[fail-safes.player_detection]
		player_detection = false
		player_detection_range = 10

	[fail-safes.movement]
		yaw_change = false
		teleport = false
		pitch_change = false
		"pitch/yaw_change_amount" = 1
		teleport_distance = 2

