
[general]
	selected_macro = 3

[warp_back]
	server_ip = "mc.hypixel.net:25565"
	warp_back_commands = "skyblock, warp garden"

[island_forager]
	debug_mode = false
	sapling_slot = 1
	bone_meal_slot = 2
	axe_slot = 3
	single_mode = false

	[island_forager.inventory]
		sapling_slot = 5
		bone_meal_slot = 4
		axe_slot = 1

	[island_forager.movement]
		"move-limit_(speed_basically)" = 3

	[island_forager.fail-safes]
		stop_on_error = true
		stop_on_empty_hand = true
		"disable_normal_fail-safes_(except_world_change)" = true
		"stop_on_yaw/pitch_change" = true

[cane]
	start_direction = 0

	[cane.timer]
		timer = 1
		row_time = "60"

[ad_macro]
	start_direction = 0

	[ad_macro.timer]
		timer = 1
		row_time = "60"

[mushroom]
	start_direction = 0
	timer = 1
	row_time = "60"

	[mushroom.obsidan_pause]
		obi_pause_time = 12
		pause_on_obi = true
		switch_direction = true

[fail-safes]

	[fail-safes.world_change]
		world_change = true
		warp_back_on_world_change = false
		warp_back_command = "/warp garden"

	[fail-safes.world]
		block_change = false

	[fail-safes.player_detection]
		player_detection = false
		range = 10

	[fail-safes.inventory]
		slot_change = false

	[fail-safes.movement]
		change_amount = 1
		yaw_change = false
		teleport = false
		pitch_change = false
		teleport_distance = 2

[undefined]
	stop_on_error = true
	"stop_on_yaw/pitch_change" = true

